//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProject.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adauga.
        /// </summary>
        public static string Adauga {
            get {
                return ResourceManager.GetString("Adauga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An fabricatie.
        /// </summary>
        public static string AnFabricatie {
            get {
                return ResourceManager.GetString("AnFabricatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulare.
        /// </summary>
        public static string Anulare {
            get {
                return ResourceManager.GetString("Anulare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentificare.
        /// </summary>
        public static string Autentificare {
            get {
                return ResourceManager.GetString("Autentificare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare asigurare.
        /// </summary>
        public static string DataExpirareAsigurare {
            get {
                return ResourceManager.GetString("DataExpirareAsigurare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare copie conforma.
        /// </summary>
        public static string DataExpirareCopieConforma {
            get {
                return ResourceManager.GetString("DataExpirareCopieConforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare ITP.
        /// </summary>
        public static string DataExpirareITP {
            get {
                return ResourceManager.GetString("DataExpirareITP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare Tahograf.
        /// </summary>
        public static string DataExpirareTahograf {
            get {
                return ResourceManager.GetString("DataExpirareTahograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare Vignette NL.
        /// </summary>
        public static string DataExpirareVignetteNL {
            get {
                return ResourceManager.GetString("DataExpirareVignetteNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data expirare Vignette UK.
        /// </summary>
        public static string DataExpirareVignetteUK {
            get {
                return ResourceManager.GetString("DataExpirareVignetteUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editeaza.
        /// </summary>
        public static string Editeaza {
            get {
                return ResourceManager.GetString("Editeaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatii Generale.
        /// </summary>
        public static string InformatiiGenerale {
            get {
                return ResourceManager.GetString("InformatiiGenerale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intoduceti email.
        /// </summary>
        public static string IntoducetiEmail {
            get {
                return ResourceManager.GetString("IntoducetiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intoduceti parola.
        /// </summary>
        public static string IntoducetiParola {
            get {
                return ResourceManager.GetString("IntoducetiParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sau parola gresita!.
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca/Brand.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numar inmatriculare.
        /// </summary>
        public static string NumarInmatriculare {
            get {
                return ResourceManager.GetString("NumarInmatriculare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvare.
        /// </summary>
        public static string Salvare {
            get {
                return ResourceManager.GetString("Salvare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterge.
        /// </summary>
        public static string Sterge {
            get {
                return ResourceManager.GetString("Sterge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValabilitateActe.
        /// </summary>
        public static string ValabilitateActe {
            get {
                return ResourceManager.GetString("ValabilitateActe", resourceCulture);
            }
        }
    }
}
