CREATE TABLE [dbo].[Drive]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Worker] UNIQUEIDENTIFIER NOT NULL,
	[Truck] UNIQUEIDENTIFIER NOT NULL,
	[Date] DATETIME NOT NULL,
	[Vlaplan] nvarchar(255) NOT NULL,
	[Vlaref] nvarchar(255) NOT NULL,
	[LoadingPlace] nvarchar(255) NOT NULL,
	[Destination] nvarchar(255) NOT NULL,
	[InitialGPSKM] decimal(12,2) NOT NULL,
	[FinalGPSKM] decimal(12,2) NOT NULL,
	[DistanceGPS] decimal(12,2) NOT NULL,
	[DistanceGpl] decimal(12,2) NOT NULL,
	[DistanceDFDS] decimal(12,2) NOT NULL,
	[Difference] decimal(12,2) NOT NULL,
	[Reason] nvarchar(MAX) NOT NULL,
	[WeightInTons] decimal(12,2) NOT NULL,
	[WorkerCosts] decimal(18,3) NULL,
	[CostsSpecification] nvarchar(MAX) NULL,
	[PayedCosts] decimal(18,3) NULL,
	[SettlementCosts] decimal(18,3) NULL,
	[TotalPayments] decimal(18,3) NOT NULL,
    [GPSInitialConsumption] decimal(12,2) NOT NULL,
	[GPSFinalConsumption] decimal(12,2) NOT NULL,
	[GPSConsumption] decimal(12,2) NOT NULL,
	[EstimatedConsumption] decimal(12,2) NOT NULL,
	[FueledKM] decimal(12,2) NULL,
	[FueledDieseKMLiters] decimal(12,2) NULL,
	[DieselValue] decimal(12,3) NULL,
	[RealConsumption] decimal(12,2) NULL,
	[AdblueLiters] decimal(12,2) NULL,
	[AdblueValue] decimal(12,2) NULL,
	CONSTRAINT FK_DRIVE_WORKER FOREIGN KEY (Worker) REFERENCES dbo.Worker (Id),
	CONSTRAINT FK_DRIVE_Truck FOREIGN KEY (Truck) REFERENCES dbo.Trucks (Id)

)
