CREATE TABLE [dbo].[DriveCosts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[CostEuro] DECIMAL(12,2) NOT NULL,
	[CostPounds] DECIMAL(12,2) NOT NULL,
	[Drive] UNIQUEIDENTIFIER  NOT NULL,
	[Specifications] NVARCHAR(300) NULL, 
    CONSTRAINT FK_DriveCosts_Drive FOREIGN KEY (Drive) REFERENCES dbo.Drive(Id)
)
