CREATE TABLE [dbo].[Drive]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Worker] UNIQUEIDENTIFIER NOT NULL,
	[Truck] UNIQUEIDENTIFIER NOT NULL,
	[Date] DATETIME NOT NULL,
	[Vlaplan] nvarchar(255) NOT NULL,
	[Vlaref] nvarchar(255) NOT NULL,
	[LoadingPlace] nvarchar(255) NOT NULL,
	[Destination] nvarchar(255) NOT NULL,
	[InitialGPSKM] int NOT NULL,
	[FinalGPSKM] int NOT NULL,
	[DistanceGPS] int NOT NULL,
	[DistanceGpl] int NOT NULL,
	[DistanceDFDS] int NOT NULL,
	[Difference] int NOT NULL,
	[Reason] nvarchar(MAX) NOT NULL,
	[WeightInTons] decimal(12,2) NOT NULL,
	[WorkerCosts] decimal(18,3) NULL,
	[CostsSpecification] nvarchar(MAX) NULL,
	[PayedCosts] decimal(18,3) NULL,
	[SettlementCosts] decimal(18,3) NULL,
	[TotalPayments] decimal(18,3) NOT NULL,
    [GPSInitialConsumption] int NOT NULL,
	[GPSFinalConsumption] int NOT NULL,
	[GPSConsumption] int NOT NULL,
	[EstimatedConsumption] int NOT NULL,
	[FueledKM] int NULL,
	[FueledDieseKMLiters] int NULL,
	[DieselValue] decimal(12,3) NULL,
	[RealConsumption] int NULL,
	[AdblueLiters] int NULL,
	[AdblueValue] int NULL,
	CONSTRAINT FK_DRIVE_WORKER FOREIGN KEY (Worker) REFERENCES dbo.Worker (Id),
	CONSTRAINT FK_DRIVE_Truck FOREIGN KEY (Truck) REFERENCES dbo.Trucks (Id)

)
