//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationWarnnings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationWarnnings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogicLayer.Helpers.NotificationWarnnings", typeof(NotificationWarnnings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atestatul soferului {0} a expirat pe data de {1}..
        /// </summary>
        internal static string CertificateExpired {
            get {
                return ResourceManager.GetString("CertificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atestatul soferului {0} va expira pe data de {1}..
        /// </summary>
        internal static string CertificateWillExpire {
            get {
                return ResourceManager.GetString("CertificateWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia conforma a camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string ConformCopyExpired {
            get {
                return ResourceManager.GetString("ConformCopyExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia conforma a camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string ConformCopyWillExpire {
            get {
                return ResourceManager.GetString("ConformCopyWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asigurarea camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string InsuranceExpired {
            get {
                return ResourceManager.GetString("InsuranceExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asigurarea camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string InsuranceWillExpire {
            get {
                return ResourceManager.GetString("InsuranceWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITP-ul camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string ITPExpired {
            get {
                return ResourceManager.GetString("ITPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITP-ul camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string ITPWillExpire {
            get {
                return ResourceManager.GetString("ITPWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizele medicale ale soferului {0} au expirat pe data de {1}..
        /// </summary>
        internal static string MedicalExpired {
            get {
                return ResourceManager.GetString("MedicalExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizele medicale ale soferului {0} vor expira pe data de {1}..
        /// </summary>
        internal static string MedicalWillExpire {
            get {
                return ResourceManager.GetString("MedicalWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisul soferului {0} a expirat pe data de {1}..
        /// </summary>
        internal static string PermitExpired {
            get {
                return ResourceManager.GetString("PermitExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permisul soferului {0} va expira pe data de {1}..
        /// </summary>
        internal static string PermitWillExpire {
            get {
                return ResourceManager.GetString("PermitWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardul tahograf soferului {0} a expirat pe data de {1}..
        /// </summary>
        internal static string TahografCardExpired {
            get {
                return ResourceManager.GetString("TahografCardExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardul tahograf soferului {0} va expira pe data de {1}..
        /// </summary>
        internal static string TahografCardWillExpire {
            get {
                return ResourceManager.GetString("TahografCardWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahograful camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string TahografExpired {
            get {
                return ResourceManager.GetString("TahografExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahograful camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string TahografWillExpire {
            get {
                return ResourceManager.GetString("TahografWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigneta NL a camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string VignetteNLExpired {
            get {
                return ResourceManager.GetString("VignetteNLExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigneta NL a camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string VignetteNLWillExpire {
            get {
                return ResourceManager.GetString("VignetteNLWillExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigneta UK a camionului cu numarul de inmatriculare {0} a expirat pe data de {1}..
        /// </summary>
        internal static string VignetteUKExpired {
            get {
                return ResourceManager.GetString("VignetteUKExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigneta UK a camionului cu numarul de inmatriculare {0} va expira pe data de {1} ..
        /// </summary>
        internal static string VignetteUKWillExpire {
            get {
                return ResourceManager.GetString("VignetteUKWillExpire", resourceCulture);
            }
        }
    }
}
